# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0002_profileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('TV/Phone/Internet', 'TV/Phone/Internet'), ('Water/Gas/Electricity', 'Water/Gas/Electricity'), ('Restaurants', 'Restaurants'), ('Gym', 'Gym'), ('Other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0, editable=False)),
                ('total', models.IntegerField(default=0, editable=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KimoniTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('User request', 'User request'), ('Kimoni suggestion', 'Kimoni suggestion'), ('Kimoni algorithm', 'Kimoni algorithm')], max_length=30)),
                ('amount', models.IntegerField(default=0, editable=False)),
                ('total', models.IntegerField(default=0, editable=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='target',
            old_name='amount',
            new_name='achieved_amount',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='risky',
            field=models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)], default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='stable',
            field=models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)], default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='achieved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='target_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='kimonitransaction',
            name='target',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='savings.Target'),
        ),
    ]
