# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20160918_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='total',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='kimonitransaction',
            old_name='total',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='stable',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='notification_days_frequency',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='purchasing_power',
            field=models.IntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'medium'), (4, 'high'), (5, 'very high')], default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='steady',
            field=models.IntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'medium'), (4, 'high'), (5, 'very high')], default=0),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kimonitransaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kimonitransaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='risky',
            field=models.IntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'medium'), (4, 'high'), (5, 'very high')], default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
